---
- name: Configure grub
  become: true

  tasks:
    - name: Add ifnames into grub config
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        backup: yes
        regexp: 'GRUB_CMDLINE_LINUX'
        line: ' net.ifnames=0'
        state: present

    - name: Add biosdevname into grub config
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        backup: yes
        regexp: 'GRUB_CMDLINE_LINUX'
        line: ' biosdevname=0'
        state: present

    - name: Generate grub configuration file
      raw: grub2-mkconfig
      args:
        executable: /bin/bash